name = "Zauner"
uuid = "ce1149fb-49fa-4541-ae6c-62019ae07d40"
version = "0.1.1"
authors = ["Steve Flammia <sflammia@gmail.com>"]

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GenericFFT = "a8297547-1b15-4a5a-a998-a2ac5f1cef28"
Hecke = "3e1990a7-5d81-5526-99ce-9ba3ff248f21"
LazilyInitializedFields = "0e77f7df-68c5-4e49-93ce-4cd80f5598bf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
ForwardDiff = "0.10 - 1.4"
GenericFFT = "0.1"
Hecke = "0.32 - 0.40"
LazilyInitializedFields = "1"
LinearAlgebra = "1.12.0"
QuadGK = "2"
Reexport = "1"
julia = "1.6"
